const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('fs')
const os = require('os')
const path = require('path')
const { startAdmin } = require('../tools/admin-server.cjs')
test('API privada: exige sesión, rechaza otro origen y publica solo en pruebas', async t => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'vortex-admin-'))
    const { server, url } = await startAdmin({ root, port: 0, password: 'test-only',syncVersion:null })
    t.after(async () => { await new Promise(resolve => server.close(resolve)); fs.rmSync(root, { recursive: true, force: true }) })
    assert.equal((await fetch(url + '/api/state')).status, 401)
    const post = (route, data, cookie, origin = url) => fetch(url + '/api/' + route, { method: 'POST', headers: { Origin: origin, 'Content-Type': 'application/json', ...(cookie ? { Cookie: cookie } : {}) }, body: JSON.stringify(data) })
    assert.equal((await post('login', { password: 'wrong' })).status, 401)
    const login = await post('login', { password: 'test-only' })
    assert.equal(login.status, 200)
    const cookie = login.headers.get('set-cookie').split(';')[0]
    assert.equal((await post('create', { id: 'vortex', version: '1.0.0' }, cookie, 'http://other.invalid')).status, 403)
    assert.equal((await post('create', { id: 'vortex', version: '1.0.0' }, cookie)).status, 200)
    assert.equal((await post('add', { id: 'vortex', revision: 0, path: 'mods/test.jar', policy: 'managed', base64: Buffer.from('fixture').toString('base64') }, cookie)).status, 200)
    assert.equal((await post('notes', { id: 'vortex', revision: 0, notes: 'stale' }, cookie)).status, 400)
    assert.equal((await post('publish', { id: 'vortex', revision: 1 }, cookie)).status, 200)
    const state = await (await fetch(url + '/api/state', { headers: { Cookie: cookie } })).json()
    assert.equal(state.channels.test.version, '1.0.0')
    assert.equal(state.channels.stable, null)
    assert.equal((await fetch(url + '/private-signing-key.pem')).status, 404)
    assert.equal((await fetch(url)).status, 200)
    const zip=new (require('adm-zip'))();zip.addFile('META-INF/neoforge.mods.toml',Buffer.from('[[dependencies.example]]\nmodId="minecraft"\nversionRange="[1.21.1]"'));const compatible=zip.toBuffer().toString('base64')
    const clone = await (await post('library/create', { version: '1.0.1', source: 'vortex' }, cookie)).json()
    assert.equal((await post('library/add', { id: clone.id, revision: 1, category: 'mods', filename: 'new.jar', replacePath: 'mods/test.jar', base64: compatible }, cookie)).status, 200)
    assert.equal((await post('library/add', { id: clone.id, revision: 2, category: 'mods', filename: 'wrong.zip', base64: 'YQ==' }, cookie)).status, 400)
    assert.equal((await post('library/add', { id: clone.id, revision: 2, category: 'config', filename: 'settings.json', base64: Buffer.from('{"enabled":true}').toString('base64') }, cookie)).status, 200)
    const config = await (await post('config/read', { id: clone.id, path: 'config/settings.json' }, cookie)).json()
    assert.equal(JSON.parse(config.text).enabled, true)
    assert.equal((await post('config/save', { id: clone.id, revision: 3, path: 'config/settings.json', text: '{broken' }, cookie)).status, 400)
    assert.equal((await post('config/save', { id: clone.id, revision: 3, path: 'config/settings.json', text: '{"enabled":false}' }, cookie)).status, 200)
    const after = await (await fetch(url + '/api/state', { headers: { Cookie: cookie } })).json()
    const updated = after.drafts.find(d => d.id === clone.id)
    assert.deepEqual(updated.files.map(f => f.path).sort(), ['config/settings.json', 'mods/new.jar'])
    assert.equal(after.drafts.find(d => d.id === 'vortex').files[0].path, 'mods/test.jar')
})
