const {test}=require('node:test')
const assert=require('node:assert/strict')
const fs=require('node:fs'),os=require('node:os'),path=require('node:path')
const {ReleaseStore,verify,applyRelease}=require('../vortex/release-store.cjs')
const {JarvisProtection}=require('../vortex/jarvis-protection.cjs')
test('Jarvis conserva sus bytes al publicar y restaurar; el catálogo no puede sustituirlos',()=>{
    const root=fs.mkdtempSync(path.join(os.tmpdir(),'vortex-jarvis-')), store=new ReleaseStore(root), protection=new JarvisProtection(root)
    const input=path.join(root,'fixture');fs.writeFileSync(input,'modificación propia')
    store.create('own','1.0.0','test');store.add('own',0,input,'resourcepacks/own.zip','managed')
    let file=store.getDraft('own').files[0]
    assert(protection.status(file).protected)
    protection.mark(file,{provider:'curseforge',projectId:123})
    assert(protection.status(file).jarvis)
    fs.writeFileSync(input,'original del catálogo')
    assert.throws(()=>store.add('own',1,input,'resourcepacks/own.zip','managed',undefined,'catalog'),/protegido/)
    const envelope=store.publish('own',1),key=fs.readFileSync(path.join(root,'public-signing-key.pem'))
    assert.equal(verify(envelope,key).files[0].sha256,file.sha256)
    const restored=store.restore('1.0.0');assert.equal(store.getDraft(restored.id).files[0].sha256,file.sha256)
    assert(protection.status(store.getDraft(restored.id).files[0]).jarvis)
    const instance=path.join(root,'instance');applyRelease(instance,envelope,key,sha=>fs.readFileSync(path.join(root,'blobs',sha)))
    assert.equal(fs.readFileSync(path.join(instance,'resourcepacks/own.zip'),'utf8'),'modificación propia')
    fs.writeFileSync(input,'segunda modificación local');store.add(restored.id,0,input,'resourcepacks/own.zip','managed')
    file=store.getDraft(restored.id).files[0];assert(protection.status(file).jarvis)
})
