const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path')
const {destinationSummary}=require('../vortex/mod-destination.cjs')
test('Distant Horizons queda excluido del servidor aunque el catálogo o una revisión antigua digan BOTH',t=>{
    const Zip=require('adm-zip'),zip=new Zip();zip.addFile('META-INF/neoforge.mods.toml',Buffer.from('[[mods]]\nmodId="distanthorizons"'))
    const review=require('../vortex/mod-destination.cjs').inspectMod(zip.toBuffer(),{client_side:'optional',server_side:'optional'})
    assert.equal(review.destination,'client');assert.equal(review.policy,true)
    const root=fs.mkdtempSync(path.join(os.tmpdir(),'vortex-policy-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}))
    fs.mkdirSync(path.join(root,'server','reviews'),{recursive:true});fs.writeFileSync(path.join(root,'server','reviews',review.sha256+'.json'),JSON.stringify({...review,destination:'both',documentation:'Revisión anterior que permitía funciones opcionales servidor'}))
    assert.equal(destinationSummary(root,review.sha256).destination,'client')
})
test('un contenedor FML requiere revisión y comprueba Java del código anidado',()=>{
    const Zip=require('adm-zip'),nested=new Zip(),outer=new Zip(),klass=Buffer.alloc(8)
    klass.writeUInt32BE(0xcafebabe);klass.writeUInt16BE(66,6);nested.addFile('Example.class',klass)
    outer.addFile('META-INF/MANIFEST.MF',Buffer.from('Manifest-Version: 1.0\r\nFMLModType: LIBRARY\r\n'))
    outer.addFile('META-INF/jarjar/example.jar',nested.toBuffer())
    const result=require('../vortex/mod-destination.cjs').inspectMod(outer.toBuffer())
    assert.equal(result.verified,false);assert.equal(result.evidence.maxJava,22);assert.match(result.reason,/Java 22/)
})
test('la clasificación persistida identifica exclusivamente el hash revisado y rechaza una revisión incompatible',t=>{
    const root=fs.mkdtempSync(path.join(os.tmpdir(),'vortex-destination-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}))
    const folder=path.join(root,'server','reviews');fs.mkdirSync(folder,{recursive:true})
    const hash='a'.repeat(64),file=path.join(folder,hash+'.json')
    const review={sha256:hash,destination:'both',documentation:'Catálogo y archivo revisados para ambos entornos',evidence:{maxJava:21}}
    fs.writeFileSync(file,JSON.stringify(review));assert.equal(destinationSummary(root,hash).destination,'both')
    assert.equal(destinationSummary(root,'b'.repeat(64)).verified,false)
    fs.writeFileSync(file,JSON.stringify({...review,sha256:'b'.repeat(64)}));assert.equal(destinationSummary(root,hash).verified,false)
    fs.writeFileSync(file,JSON.stringify({...review,evidence:{maxJava:22}}));assert.equal(destinationSummary(root,hash).verified,false)
    fs.writeFileSync(file,'{broken');assert.equal(destinationSummary(root,hash).verified,false)
    assert.equal(destinationSummary(root,'../reviews/anything').verified,false)
})
