const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('fs')
const os = require('os')
const path = require('path')
const { ReleaseStore, applyRelease, verify, safe } = require('../vortex/release-store.cjs')
function setup(t) {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'vortex-release-'))
    t.after(() => fs.rmSync(root, { recursive: true, force: true }))
    const store = new ReleaseStore(path.join(root, 'admin'))
    const source = (name, data) => { const f = path.join(root, name); fs.writeFileSync(f, data); return f }
    const publish = (name, version, files) => {
        store.create(name, version, 'test')
        files.forEach((f, i) => store.add(name, i, source('input-' + i, f[1]), f[0], f[2] || 'managed'))
        return store.publish(name, files.length)
    }
    const apply = (envelope, options) => applyRelease(path.join(root, 'instance'), envelope, fs.readFileSync(path.join(root, 'admin/public-signing-key.pem')), sha => fs.readFileSync(path.join(root, 'admin/blobs', sha)), options)
    return { root, store, source, publish, apply }
}
test('borradores con control de revisión, publicaciones inmutables y firma', t => {
    const s = setup(t)
    const envelope = s.publish('a', '1.0.0', [['mods/a.jar', 'a']])
    assert.throws(() => s.store.edit('a', 0, () => {}), /Conflicto/)
    fs.writeFileSync(path.join(s.root,'admin/channels/stable.json'),JSON.stringify({version:'1.0.0'}))
    assert.throws(() => s.store.publish('a', 1), /inmutable/)
    assert.throws(() => s.store.publish('a', 1, 'stable'), /Solo publicación/)
    assert.throws(() => verify({ ...envelope, payload: envelope.payload + ' ' }, fs.readFileSync(path.join(s.root, 'admin/public-signing-key.pem'))), /Firma/)
    assert.equal(JSON.parse(fs.readFileSync(path.join(s.root, 'admin/channels/test.json'))).version, '1.0.0')
})
test('A a B conserva ajustes y mundos, retira solo archivos administrados y reutiliza hashes', t => {
    const s = setup(t)
    s.apply(s.publish('a', '1.0.0', [['mods/a.jar', 'a'], ['options.txt', 'default', 'seed']]))
    fs.writeFileSync(path.join(s.root, 'instance/options.txt'), 'player settings')
    fs.mkdirSync(path.join(s.root, 'instance/saves'))
    fs.writeFileSync(path.join(s.root, 'instance/saves/world'), 'world')
    const release = s.publish('b', '1.0.1', [['mods/b.jar', 'b'], ['options.txt', 'new default', 'seed']])
    assert.equal(s.apply(release).changed, 2)
    assert.equal(fs.existsSync(path.join(s.root, 'instance/mods/a.jar')), false)
    assert.equal(fs.readFileSync(path.join(s.root, 'instance/options.txt'), 'utf8'), 'player settings')
    assert.equal(fs.readFileSync(path.join(s.root, 'instance/saves/world'), 'utf8'), 'world')
    assert.equal(s.apply(release).changed, 0)
})
test('fallo durante aplicación restaura la versión anterior', t => {
    const s = setup(t)
    s.apply(s.publish('a', '1.0.0', [['mods/a.jar', 'a']]))
    const b = s.publish('b', '1.0.1', [['mods/b.jar', 'b']])
    assert.throws(() => s.apply(b, { afterChange() { throw Error('Disco bloqueado') } }), /Disco/)
    assert.equal(fs.readFileSync(path.join(s.root, 'instance/mods/a.jar'), 'utf8'), 'a')
    assert.equal(fs.existsSync(path.join(s.root, 'instance/mods/b.jar')), false)
    assert.equal(JSON.parse(fs.readFileSync(path.join(s.root, 'instance/.vortex-owned.json'))).version, '1.0.0')
})
test('rechaza blobs corruptos, rutas Windows peligrosas y archivos personales coincidentes', t => {
    const s = setup(t)
    const a = s.publish('a', '1.0.0', [['mods/a.jar', 'a']])
    const manifest = JSON.parse(a.payload)
    const blob = path.join(s.root, 'admin/blobs', manifest.files[0].sha256)
    fs.writeFileSync(blob, 'corrupt')
    assert.throws(() => s.apply(a), /corrupta/)
    for(const relative of ['../outside', 'mods/con.jar', 'mods/a.jar:stream', 'mods/A./file']) assert.throws(() => safe(s.root, relative), /inválida/)
    fs.mkdirSync(path.join(s.root, 'instance/mods'), { recursive: true })
    fs.writeFileSync(path.join(s.root, 'instance/mods/a.jar'), 'personal')
    assert.throws(() => s.apply(a), /ajeno/)
})
