const {test} = require('node:test')
const assert = require('node:assert/strict')
const fs = require('fs'), os = require('os'), path = require('path')
const {hash} = require('../vortex/release-store.cjs')
const {restoreEmptySelection} = require('../vortex/resourcepack-options.cjs')
test('recupera orden y formatos aceptados sin cambiar controles ni activar archivos retirados', t=>{
    const dir=fs.mkdtempSync(path.join(os.tmpdir(),'vortex-options-'))
    t.after(()=>fs.rmSync(dir,{recursive:true,force:true}))
    fs.mkdirSync(path.join(dir,'resourcepacks'))
    fs.writeFileSync(path.join(dir,'resourcepacks/fonts.zip'),'fonts')
    fs.writeFileSync(path.join(dir,'options.txt'),'volume:0.3\nresourcePacks:[]\nincompatibleResourcePacks:[]\nkey_key.forward:87\n')
    const bytes=Buffer.from('resourcePacks:["vanilla","file/missing.zip","file/fonts.zip"]\nincompatibleResourcePacks:["file/fonts.zip"]\nvolume:1\n')
    const manifest={files:[{path:'options.txt',sha256:hash(bytes),size:bytes.length},{path:'resourcepacks/fonts.zip'},{path:'resourcepacks/missing.zip'}]}
    assert.equal(restoreEmptySelection(dir,manifest,()=>bytes),true)
    const result=fs.readFileSync(path.join(dir,'options.txt'),'utf8')
    assert.match(result,/resourcePacks:\["vanilla","file\/fonts.zip"\]/)
    assert.match(result,/incompatibleResourcePacks:\["file\/fonts.zip"\]/)
    assert.match(result,/volume:0.3/)
    assert.match(result,/key_key.forward:87/)
    assert.equal(restoreEmptySelection(dir,manifest,()=>{throw Error('No debería leer')}),false)
    assert.equal(fs.readFileSync(path.join(dir,'options.txt'),'utf8'),result)
    fs.writeFileSync(path.join(dir,'options.txt'),'resourcePacks:[]\n')
    assert.throws(()=>restoreEmptySelection(dir,manifest,()=>Buffer.from('corrupto')),/alteradas/)
})
