const { test } = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { ReleaseStore } = require('../vortex/release-store.cjs')

test('Crear copia la publicación, incrementa cada diez parches y bloquea su edición', () => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'vortex-version-flow-'))
    const store = new ReleaseStore(root)
    store.create('original', '1.0.9', 'test')
    const source = path.join(root, 'fixture')
    fs.writeFileSync(source, '{}')
    store.add('original', 0, source, 'config/example.json', 'seed')
    store.publish('original', 1)
    assert.throws(() => store.edit('original', 1, d => { d.notes = 'cambio' }), /crear una nueva versión/)
    const next = store.createNext('new', 'original')
    assert.equal(next.version, '1.1.0')
    assert.deepEqual(store.getDraft(next.id).files, store.getDraft('original').files)
    const fix = store.createNext('fix', 'original')
    assert.equal(fix.version, '1.0.9 fixed')
    assert.throws(() => store.createNext('fix', 'original'), /Ya existe/)
    store.edit(fix.id, 0, d => { d.editorDrafts = { 'config/example.json': '{ incompleto' } })
    assert.equal(new ReleaseStore(root).getDraft(fix.id).editorDrafts['config/example.json'], '{ incompleto')
    assert.throws(() => store.publish(fix.id, 1), /configuraciones pendientes/)
    store.edit(fix.id, 1, d => { delete d.editorDrafts })
    store.publish(fix.id, 2)
    assert(store.isPublished(store.getDraft(fix.id)))
})
