const fs=require('fs'),path=require('path'),crypto=require('crypto')
const {safe,atomic}=require('./release-store.cjs'),{accountRole}=require('./account-role.cjs')
const hash=bytes=>crypto.createHash('sha256').update(bytes).digest('hex')
class PersonalFiles {
    constructor(configFile,{authorize=accountRole}={}){this.configFile=configFile;this.authorize=authorize}
    async context(){const config=JSON.parse(fs.readFileSync(this.configFile)),account=config.authenticationDatabase?.[config.selectedAccount];if(await this.authorize(account)!=='Administrador')throw Error('Solo el administrador puede administrar archivos personales');const latest=JSON.parse(fs.readFileSync(this.configFile));if(latest.selectedAccount!==config.selectedAccount)throw Error('La cuenta cambió');if(!/^[a-z0-9._-]{1,80}$/i.test(config.selectedServer))throw Error('Instancia inválida');const instance=path.join(path.resolve(config.settings.launcher.dataDirectory),'profiles',account.uuid.replace(/-/g,'').toLowerCase(),'instances',config.selectedServer);if(!fs.existsSync(instance))throw Error('Instala primero esta versión');if(fs.existsSync(path.join(instance,'.vortex-update.lock')))throw Error('Espera a que termine la actualización');return {instance,account}}
    category(value){if(!['mods','resourcepacks','shaderpacks','config'].includes(value))throw Error('Categoría inválida');return value}
    target(instance,name){if(!['mods','resourcepacks','shaderpacks','config'].includes(name.split('/')[0]))throw Error('Archivo fuera del perfil');return safe(instance,name)}
    editable(bytes){return bytes.length<=2*1024*1024 && !bytes.includes(0) && Buffer.from(bytes.toString('utf8')).equals(bytes)}
    async list(category){this.category(category);const {instance}=await this.context(),files=[];const walk=(relative)=>{const dir=safe(instance,relative);if(!fs.existsSync(dir))return;for(const e of fs.readdirSync(dir,{withFileTypes:true})){const name=relative+'/'+e.name;if(e.isSymbolicLink())continue;if(e.isDirectory()){walk(name);continue}const target=safe(instance,name),size=fs.statSync(target).size;files.push({path:name,size,editable:category==='config'&&size<=2*1024*1024&&this.editable(fs.readFileSync(target))})}};walk(category);if(category==='mods'){const index=path.join(instance,'.vortex-vault/index.json');if(fs.existsSync(index))for(const e of JSON.parse(fs.readFileSync(index)))if(e.path.startsWith('mods/')&&!files.some(f=>f.path===e.path))files.push({path:e.path,encrypted:true,editable:false})}return files.sort((a,b)=>Number(b.editable)-Number(a.editable)||a.path.localeCompare(b.path))}
    async read(name){const {instance}=await this.context();if(!name.startsWith('config/'))throw Error('Solo se editan configuraciones');const bytes=fs.readFileSync(this.target(instance,name));if(!this.editable(bytes))throw Error('Esta configuración no se puede editar como texto');return {text:bytes.toString('utf8'),sha256:hash(bytes)}}
    async write(name,text,expectedHash){const {instance}=await this.context();if(!name.startsWith('config/')||typeof text!=='string'||Buffer.byteLength(text)>2*1024*1024||text.includes('\0'))throw Error('Configuración inválida');const target=this.target(instance,name),previous=fs.readFileSync(target);if(!this.editable(previous)||hash(previous)!==expectedHash)throw Error('El archivo cambió; vuelve a abrirlo antes de guardar');atomic(target,Buffer.from(text));return {saved:true}}
    async remove(name){const {instance}=await this.context(),target=this.target(instance,name);const index=path.join(instance,'.vortex-vault/index.json');if(fs.existsSync(index)){const entries=JSON.parse(fs.readFileSync(index)),entry=entries.find(e=>e.path===name);if(entry){const encrypted=safe(instance,'.vortex-vault/'+entry.sha256+'.vxmod');if(fs.existsSync(encrypted))fs.unlinkSync(encrypted);atomic(index,JSON.stringify(entries.filter(e=>e.path!==name)))}}if(fs.existsSync(target)){if(!fs.statSync(target).isFile())throw Error('Solo se eliminan archivos');fs.unlinkSync(target)}const marker=path.join(instance,'.vortex-personal.json'),state=fs.existsSync(marker)?JSON.parse(fs.readFileSync(marker)):{deleted:[]};state.deleted=[...new Set([...(state.deleted||[]),name])];atomic(marker,JSON.stringify(state));return {removed:true}}
    async replace(name,source){const {instance}=await this.context();if(!name.startsWith('config/'))throw Error('Solo se sustituyen configuraciones');const target=this.target(instance,name);if(!fs.existsSync(target)||!fs.statSync(target).isFile()||fs.lstatSync(source).isSymbolicLink()||!fs.statSync(source).isFile())throw Error('Archivo no permitido');atomic(target,fs.readFileSync(source));return {replaced:true}}
    async add(category,sources){this.category(category);const {instance}=await this.context();const extensions=category==='mods'?['.jar']:category==='config'?['.json','.toml','.cfg','.properties','.txt','.yaml','.yml','.ini','.conf','.snbt','.xml']:['.zip'];for(const source of sources){const name=category+'/'+path.basename(source);if(!extensions.includes(path.extname(source).toLowerCase())||fs.lstatSync(source).isSymbolicLink()||!fs.statSync(source).isFile())throw Error('Archivo no permitido');atomic(this.target(instance,name),fs.readFileSync(source));const marker=path.join(instance,'.vortex-personal.json');if(fs.existsSync(marker)){const state=JSON.parse(fs.readFileSync(marker));state.deleted=(state.deleted||[]).filter(p=>p!==name);atomic(marker,JSON.stringify(state))}}return {added:sources.length}}
}
module.exports={PersonalFiles}
