(() => {
    const section=document.createElement('section');section.className='serverConsole';section.innerHTML='<div class="consoleHeader"><h3>Consola del servidor</h3><span id="consoleState" role="status">Desconectada</span><button id="clearConsole" class="secondary" type="button">Limpiar vista</button></div><pre id="consoleOutput" tabindex="0" aria-label="Salida de la consola del servidor"></pre><form id="consoleCommand"><label for="consoleInput">Enviar comando</label><div><input id="consoleInput" autocomplete="off" spellcheck="false" placeholder="Escribe un comando del servidor…" maxlength="2000"><button id="sendConsole" type="submit">Enviar</button></div><p id="consoleMessage" role="status"></p></form>'
    document.getElementById('serverContent').querySelector('h2').after(section)
    const $=id=>document.getElementById(id);let cursor=0,reading=false,lastCommand=''
    async function read(){if(panel!=='server' || reading || document.hidden)return;reading=true;try{const result=await api('server/console?since='+cursor),output=$('consoleOutput'),atBottom=output.scrollTop+output.clientHeight>=output.scrollHeight-35;for(const line of result.lines){const node=document.createElement('span');node.textContent=line.text+'\n';output.append(node)}while(output.children.length>500)output.firstChild.remove();cursor=result.cursor;if(atBottom)output.scrollTop=output.scrollHeight;$('consoleState').textContent={connected:'En directo',connecting:'Conectando…',disconnected:'Reconectando…',error:'No se pudo conectar · Se reintentará'}[result.state] || 'Sin verificar';$('consoleState').dataset.state=result.state}catch{$('consoleState').textContent='Conexión no disponible · Se reintentará'}finally{reading=false}}
    $('consoleCommand').onsubmit=async event=>{event.preventDefault();const command=$('consoleInput').value.trim();if(!command)return;$('sendConsole').disabled=true;try{await api('server/command',{command});lastCommand=command;$('consoleInput').value='';$('consoleMessage').textContent='Comando enviado';await read()}catch(error){$('consoleMessage').textContent=error.message}finally{$('sendConsole').disabled=false;$('consoleInput').focus()}}
    $('consoleInput').onkeydown=event=>{if(event.key==='ArrowUp'){event.preventDefault();$('consoleInput').value=lastCommand}}
    $('clearConsole').onclick=()=>$('consoleOutput').replaceChildren()
    document.getElementById('serverTab').addEventListener('click',()=>queueMicrotask(read));const timer=setInterval(read,1500);window.addEventListener('pagehide',()=>clearInterval(timer),{once:true})
})()
