/* Presentación Vortex: conserva controles, operaciones y permisos originales. */
(() => {
const $=id=>document.getElementById(id)
const paths={create:'M6 3h8l4 4v14H6z M14 3v5h4',add:'M12 5v14 M5 12h14',library:'M3 4h6l3 3 3-3h6v16h-6l-3 2-3-2H3z M12 7v15',server:'M4 4h16v6H4z M4 14h16v6H4z M7 7h1 M7 17h1',publish:'M3 10l18-7-7 18-4-7z M10 14l11-11',mods:'M12 2l9 5v10l-9 5-9-5V7z M3 7l9 5 9-5 M12 12v10',resourcepacks:'M4 20l5-2 11-11-3-3L6 15z',shaderpacks:'M12 7a5 5 0 1 0 0 10 5 5 0 0 0 0-10 M12 2v2 M12 20v2 M2 12h2 M20 12h2 M5 5l2 2 M17 17l2 2 M5 19l2-2 M17 7l2-2',config:'M9 3h6l1 4 4 2v6l-4 2-1 4H9l-1-4-4-2V9l4-2z M12 9a3 3 0 1 0 0 6 3 3 0 0 0 0-6'}
function icon(name){const s=document.createElementNS('http://www.w3.org/2000/svg','svg');s.setAttribute('viewBox','0 0 24 24');s.setAttribute('aria-hidden','true');const p=document.createElementNS(s.namespaceURI,'path');p.setAttribute('d',paths[name] || paths.config);s.append(p);return s}
function make(tag,className,text){const e=document.createElement(tag);e.className=className || '';if(text)e.textContent=text;return e}
const header=document.querySelector('header');header.className='appHeader'
const brand=make('div','brand'),logo=make('img');logo.src='/vortex-logo.png';logo.alt='';const label=make('div');label.append(make('strong','','VORTEX'),make('span','','Panel de administración'));brand.append(logo,label)
const topbar=make('div','topbar');topbar.append($('targetBadge'),make('span','adminIdentity','Administración'));header.replaceChildren(brand,topbar)
const nav=document.querySelector('.mainTabs');for(const key of ['create','add','library','server','publish']){const b=$(key+'Tab');b.prepend(icon(key));nav.insertBefore(b,nav.querySelector('.workingVersion'))}
document.querySelector('.packHeader .eyebrow').hidden=true
const stats=make('div','summaryGrid');stats.id='dashboardStats'
for(const [category,title] of [['mods','Mods'],['resourcepacks','Resourcepacks'],['shaderpacks','Shaders'],['server','Servidor']]){const card=make('div','summaryCard '+category),i=make('span','summaryIcon');i.append(icon(category));const text=make('div');text.append(make('strong','',category==='server'?'Servidor':'—'),make('span','summaryLabel',category==='server'?'Comprobando…':title));card.append(i,text);card.id='summary-'+category;stats.append(card)}
document.querySelector('.packHeader').after(stats)
const layout=make('div','libraryLayout');layout.id='libraryLayout';$('library').before(layout);layout.append($('library'))
const aside=make('aside','dashboardAside');aside.setAttribute('aria-label','Resumen de la versión');aside.innerHTML='<section class="inspectorCard"><h2>Cambios de esta versión</h2><div id="changesPreview"></div><p class="autosaveCaption">Todos los cambios se guardan automáticamente</p></section><section class="inspectorCard"><h2>Servidor Vortex <span id="compactOnline" class="statusPill">Comprobando</span></h2><dl class="serverDetails"><div><dt>Jugadores</dt><dd id="compactPlayers">—</dd></div><div><dt>Dirección IP</dt><dd id="compactAddress">—</dd></div></dl><button id="openServer" class="secondary fullWidth">Ver servidor</button></section><section class="inspectorCard"><h2>Publicación del pack</h2><ol class="publishStepper"><li><span>1</span>En prueba</li><li><span>2</span>Probar versión</li><li><span>3</span>Publicar oficialmente</li></ol><p id="compactTestStatus"></p><button id="openPublish" class="secondary fullWidth">Ver publicación</button></section>'
layout.append(aside);$('openServer').onclick=()=>$('serverTab').click();$('openPublish').onclick=()=>$('publishTab').click()
const scope=make('div','scopeSwitcher');scope.setAttribute('aria-label','Biblioteca');for(const [value,label] of [['client','Launcher (cliente)'],['server','Servidor']]){const b=make('button','',label);b.dataset.scope=value;b.onclick=()=>{$('libraryScope').value=value;$('libraryScope').dispatchEvent(new Event('change'))};scope.append(b)}$('library').prepend(scope);$('libraryScope').closest('label').classList.add('originalScope')
$('search').placeholder='Buscar en la biblioteca…';$('search').closest('label').classList.add('searchLabel')
const headings=make('div','libraryHeadings');for(const t of ['Contenido','Versión','Destino','Acciones'])headings.append(make('span','',t));document.querySelector('.configBrowser').before(headings)
const footer=make('div','libraryFooter');footer.id='libraryFooter';$('content').after(footer)
function paginate(){const rows=[...$('content').querySelectorAll('.fileRow')];for(const row of rows)row.hidden=false;footer.textContent=rows.length+' archivos'}
function sync(){const draft=current(),next=panel,scope=libraryScope;layout.hidden=next!=='library' || !draft;document.body.dataset.panel=next;const copy={library:['Biblioteca del pack','Gestiona el contenido del cliente y del servidor'],create:['Crear nueva versión','Prepara el siguiente paso de Vortex'],add:['Añadir contenido','Encuentra contenido compatible con tu versión'],server:['Servidor Vortex','Gestiona el servidor y revisa los cambios pendientes'],publish:['Publicación del pack','Prueba la versión antes de distribuirla a los jugadores']}[next];if(copy){document.querySelector('.packHeader h1').textContent=copy[0];document.querySelector('.headerActions p').textContent=copy[1]}for(const category of ['mods','resourcepacks','shaderpacks'])$('summary-'+category).querySelector('strong').textContent=draft?draft.files.filter(f=>f.path.startsWith(category+'/')).length:'—';for(const b of document.querySelectorAll('[data-scope]'))b.setAttribute('aria-pressed',String(b.dataset.scope===scope));$('changesPreview').replaceChildren();for(const n of (draft?.automaticNotes || []).slice(-4).reverse())$('changesPreview').append(make('p','changeItem',n.text));if(!$('changesPreview').children.length)$('changesPreview').append(make('p','muted','Sin cambios registrados en esta versión'));const protectedCount=draft?.files.filter(f=>f.protection?.protected).length || 0;if(protectedCount)$('changesPreview').append(make('p','protectedSummary',protectedCount+' archivos protegidos'));$('compactTestStatus').textContent=draft?.testResult?.eligible?'Prueba aprobada · Lista para publicar':'Disponible después de una prueba exitosa';document.querySelector('.publishStepper li:first-child').lastChild.textContent=draft?.status==='test'?'En prueba':'Sin publicar';const stage=draft?.status==='stable'?3:draft?.testResult?.eligible?2:1;document.querySelectorAll('.publishStepper li').forEach((e,i)=>e.classList.toggle('current',i+1===stage));$('openPublish').textContent=draft?.testResult?.eligible?'Revisar y publicar oficialmente':'Ver publicación';decorateRows(draft,scope);paginate()}
function decorateRows(draft,scope){if(!['mods','resourcepacks','shaderpacks','plugins'].includes(category))return;for(const row of $('content').querySelectorAll('.fileRow:not(.tableRow)')){row.classList.add('tableRow');const filename=row.querySelector('.libraryFilename')?.textContent,title=row.querySelector('h3')?.firstChild?.textContent;const files=scope==='server'?serverLibrary?.files:draft?.files,file=files?.find(f=>filename?f.path.split('/').at(-1)===filename:(f.display?.title || f.source?.title || f.path.split('/').at(-1))===title);const actions=row.querySelector('.fileActions');actions.before(make('span','fileVersion',file?.source?.version || '—'),make('span','fileDestination',scope==='server'?'Servidor':'Por revisar'));const menu=make('details','rowMenu'),summary=make('summary','','⋮');summary.setAttribute('aria-label','Más acciones del archivo');menu.append(summary);const inner=make('div','rowMenuItems');for(const b of [...actions.children]){if(b.classList.contains('updateButton') || b.textContent==='Actualizar')continue;inner.append(b)}if(inner.children.length){menu.append(inner);actions.append(menu)}if(file?.protection?.protected){const lock=make('span','protectedLock','◇');lock.title=file.protection.reason || 'Archivo protegido';actions.prepend(lock)}}}
let loading=false;async function poll(){if(loading)return;loading=true;try{const r=await api('server/status'),players=r.players?r.players.online+'/'+r.players.max:'—',status=r.online?'Online':'Offline';$('summary-server').querySelector('.summaryLabel').textContent=status+' · '+players;$('summary-server').dataset.online=String(r.online);$('compactOnline').textContent=status;$('compactOnline').dataset.online=String(r.online);$('compactPlayers').textContent=players;$('compactAddress').textContent=r.hostname+':'+r.port}catch{$('compactOnline').textContent='Sin verificar'}finally{loading=false}}
window.VortexDesign={sync};poll();const timer=setInterval(()=>{sync();poll()},30000);window.addEventListener('pagehide',()=>clearInterval(timer),{once:true})
document.addEventListener('click',()=>queueMicrotask(sync));document.addEventListener('change',()=>queueMicrotask(sync));const observer=new MutationObserver(sync);observer.observe($('content'),{childList:true});observer.observe($('workingStatus'),{childList:true});queueMicrotask(sync)
})()
